package javapro;

import java.util.ArrayList;

public class ProducerConsumerLab {

    // SharedBuffer - Thread-safe bounded buffer

    static class SharedBuffer {
        private final ArrayList<Integer> buffer;
        private final int capacity;

        public SharedBuffer(int capacity) {
            this.buffer = new ArrayList<>();
            this.capacity = capacity;
            System.out.println("Buffer created with capacity: " + capacity);
        }

        public synchronized void produce(int value) throws InterruptedException {
            while (buffer.size() >= capacity) {
                System.out.println("[Producer] Buffer FULL - waiting...");
                wait();
            }
            buffer.add(value);
            System.out.println("[Producer] Produced: " + value + " | Buffer: " + buffer);
            notifyAll();
        }

        public synchronized int consume() throws InterruptedException {
            while (buffer.isEmpty()) {
                System.out.println("[Consumer] Buffer EMPTY - waiting...");
                wait();
            }
            int value = buffer.remove(0);
            System.out.println("[Consumer] Consumed: " + value + " | Buffer: " + buffer);
            notifyAll();
            return value;
        }
    }

    // Implement Producer class
    static class Producer implements Runnable {
        // Declare a private instance variable to hold the reference to the shared buffer
        private SharedBuffer buffer;

        // Add constructor
        public Producer(SharedBuffer buffer) {
            // Initialize the buffer field
            // Assign the buffer passed in the parameter to our instance variable
            this.buffer = buffer;
        }

        // Implement run() method
        @Override
        public void run() {
            // Use a try-catch block to handle potential InterruptedExceptions that can occur during thread execution
            try {
                // Loop 10 times to produce exactly 10 items
                for (int i = 0; i < 10; i++) {
                    // Call the synchronized produce method on our shared buffer to add the current value
                    buffer.produce(i);
                }
                // Print a message indicating all 10 items were produced
                System.out.println("[Producer] finished producing 10 items");
            } catch (InterruptedException e) {
                // Catch the exception and notify the user
                System.out.println("[Producer] was interrupted");
            }
        }
    }

    // Implement Consumer class
    static class Consumer implements Runnable {
        // Add private SharedBuffer field
        private SharedBuffer buffer;

        // Add constructor
        public Consumer(SharedBuffer buffer) {
            // Initialize the buffer field
            // Link the shared buffer passed to the constructor to the class's internal field
            this.buffer = buffer;
        }

        // Implement run() method
        @Override
        public void run() {
            // Wrap our execution in a try-catch block to handle InterruptedExceptions safely
            try {
                // Loop exactly 10 times to consume the 10 items generated by the producer
                for (int i = 0; i < 10; i++) {
                    // Call the synchronized consume method on the shared buffer to remove and return the next item
                    buffer.consume();
                }
                // Output a message confirming the consumer is finished
                System.out.println("[Consumer] finished consuming 10 items");
            } catch (InterruptedException e) {
                // Catch interruptions and print an error message
                System.out.println("[Consumer] was interrupted");
            }
        }
    }

    // Main method 
    public static void main(String[] args) {
        SharedBuffer buffer = new SharedBuffer(5);

        Producer producer = new Producer(buffer);
        Consumer consumer = new Consumer(buffer);

        Thread producerThread = new Thread(producer);
        Thread consumerThread = new Thread(consumer);

        System.out.println();
        producerThread.start();
        consumerThread.start();

        try {
            producerThread.join();
            consumerThread.join();
        } catch (InterruptedException e) {
            System.out.println("Main thread interrupted");
            return;
        }

        System.out.println("\nAll threads completed successfully!");
    }
}
